#!/bin/bash

IMG_PATH=$HOME/Pictures/screenshots/
FORMAT=.png				# maim sup png/jpg

prog="1.fullscreen
2.section"

cmd=$(dmenu -l 2 -nf '#f0f0f0' -nb '#353535' -sf '#f0f0f0' -sb '#4184F3' -p 'Screenshot Type:' <<< "$prog")

function input_name {
	name=$(dmenu -nf '#f0f0f0' -nb '#353535' -sf '#f0f0f0' -sb '#4184F3' -p 'Name:')
	if [[ $name == '' ]]; then
		exit
	fi
}
	
case ${cmd%% *} in
	1.fullscreen) 
		input_name
		maim $IMG_PATH$name$FORMAT && notify-send -u low 'Maim' 'Fullscreen SS taken!' ;;
	2.section) 
		input_name
		maim -s $IMG_PATH$name$FORMAT && notify-send -u low 'Maim' 'Section SS taken!' ;;
*) exec "'${cmd}'" ;;
esac
